name: Trigger Main Site Deployment

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    name: Notify Main Repository
    steps:
      - name: Trigger deployment in main repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/elskow/helmyl.com/dispatches \
            -d '{"event_type":"content-updated","client_payload":{"repository":"'"$GITHUB_REPOSITORY"'","ref":"'"$GITHUB_REF"'","sha":"'"$GITHUB_SHA"'"}}'

      - name: Notify completion
        run: |
          echo "✅ Successfully triggered deployment in main repository"
          echo "📦 Repository: $GITHUB_REPOSITORY"
          echo "🌿 Ref: $GITHUB_REF"
          echo "📝 SHA: $GITHUB_SHA"
          echo ""
          echo "Check deployment status at: https://github.com/elskow/helmyl.com/actions"
